config/routes.rb
Rails.application.routes.draw do
  root to: "games#home"
  get 'new_game', to: 'games#new_game'
  resources :games, except: [:destroy]
  # get '/new',  to: 'games#new'
  # get '/show', to: 'games#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  # Saves the board in the database as an object, and allows you to retrieve as the same object
  serialize :board

  include GamesHelper
  include ActiveModel::Validations

  attr_accessor :board

  validates :board, :presence => true

  def initialize
    super
    self.board = ["0", "1", "2", "3", "4", "5", "6", "7", "8"]
    @com = "X" # the computer's marker
    @hum = "O" # the user's marker
  end

  def update_board(player, row, column)
    # TODO
  end

  # Returns the current_player
  # @return [String] 'x' or 'o'
  def current_player
    # TODO
  end

  # Plays the game
  #
  # @returns winner
  # updates the board
  # call #WINNER AFTER each move, not before
  def play(row, column)
    # TODO
  end

  # @return [Boolean] returns true if there is a winner, false otherwise
  def winner
    # TODO
  end


  # The below methods can only be accessed by methods in this class
  private

  # Establishes winner in row
  def check_rows_for_winner
    # TODO
  end

  # Establishes winner in columns
  def check_columns_for_winner
    # TODO
  end

  # Establishes winner diagonally
  def check_diagonals_for_winner
    # TODO
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def home
    @game = Game.new
  end

  def new
    @game = Game.new
  end

  def new_game
     @game = Game.new
  end

  def start_game
    # loop through until the game was won or tied
    until game_is_over(@board) || tie(@board)
      get_human_spot
      if !game_is_over(@board) && !tie(@board)
        eval_board
      end
      puts " #{@board[0]} | #{@board[1]} | #{@board[2]} \n===+===+===\n #{@board[3]} | #{@board[4]} | #{@board[5]} \n===+===+===\n #{@board[6]} | #{@board[7]} | #{@board[8]} \n"
    end
    puts "Game over"
  end

  def get_human_spot
    spot = nil
    until spot
      spot = gets.chomp.to_i
      if @board[spot] != "X" && @board[spot] != "O"
        @board[spot] = @hum
      else
        spot = nil
      end
    end
  end

  def eval_board
    spot = nil
    until spot
      if @board[4] == "4"
        spot = 4
        @board[spot] = @com
      else
        spot = get_best_move(@board, @com)
        if @board[spot] != "X" && @board[spot] != "O"
          @board[spot] = @com
        else
          spot = nil
        end
      end
    end
  end

  def get_best_move(board, next_player, depth = 0, best_score = {})
    available_spaces = []
    best_move = nil
    board.each do |s|
      if s != "X" && s != "O"
        available_spaces << s
      end
    end
    available_spaces.each do |as|
      board[as.to_i] = @com
      if game_is_over(board)
        best_move = as.to_i
        board[as.to_i] = as
        return best_move
      else
        board[as.to_i] = @hum
        if game_is_over(board)
          best_move = as.to_i
          board[as.to_i] = as
          return best_move
        else
          board[as.to_i] = as
        end
      end
    end
    if best_move
      return best_move
    else
      n = rand(0..available_spaces.count)
      return available_spaces[n].to_i
    end
  end

  def game_is_over(b)

    [b[0], b[1], b[2]].uniq.length == 1 ||
    [b[3], b[4], b[5]].uniq.length == 1 ||
    [b[6], b[7], b[8]].uniq.length == 1 ||
    [b[0], b[3], b[6]].uniq.length == 1 ||
    [b[1], b[4], b[7]].uniq.length == 1 ||
    [b[2], b[5], b[8]].uniq.length == 1 ||
    [b[0], b[4], b[8]].uniq.length == 1 ||
    [b[2], b[4], b[6]].uniq.length == 1
  end

  def tie(b)
    b.all? { |s| s == "X" || s == "O" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "TicTacToe"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def display_board
    "#{display_line(0)}" +
    "- - -\n" +
    "#{display_line(1)}" +
    "- - -\n" +
    "#{display_line(2)}"
  end

  def display_element(row, column)
    element = board[row][column]
    if element
      element
    else
      ' '
    end
  end

  def display_line(row)
    "#{display_element(row,0)}|#{display_element(row,1)}|#{display_element(row,2)}\n"
  end

  def create_cell_class(row, column)
    case row

    when 0
      case column
      when 0
        'top left'
      when 1
        "top vertical-mid"
      when 2
        "top right"
      end

    when 1
      case column
      when 0
        "left horizontal-mid"
      when 1
        "vertical-mid horizontal-mid"
      when 2
        "right horizontal-mid"
      end

    when 2
      case column
      when 0
        "left bottom"
      when 1
        "bottom vertical-mid"
      when 2
        "bottom right"
      end

    end
  end
end

app/views/games/_board.html.erb
<%= form_for(@game) do |g| %>
  <%= g.hidden_field :row, :value => row %>
  <%= g.hidden_field :column, :value => column %>
  <%= g.submit "#{row}, #{column}", class: "big-btn btn btn-large btn-primary" %>
<% end %>

app/views/games/home.html.erb
<div class='container home-box'>
  <h1>Game Rules</h1>
  <h3>1. Are you ready to play the game? Click the "START" below.</h3>
  <h3>2. Click "Start Game" to start.</h3>
  <h3>3. Play again? Click the "Reset" on the upright before you hit "Start Game."  </h3>
  <h2 class='btn btn-primary'><%=link_to "START", new_game_path %></h2>
</div>

app/views/games/index.html.erb
<div class="center">
  <h1><!-- TODO --></h1>
  <%#= link_to "TODO", new_path, class: "btn btn-large primary" %>
</div>

app/views/games/new.html.erb
<%= @game.board[0] %>
<br>
<%= @game.board[1] %>
<br>
<%= @game.board[2] %>

app/views/games/new_game.html.erb
<div class='container'>
  <div>
    <table class='board' id='home-board'>
      <tbody>
        <tr>
          <td id='grid-0' class='left top'><a><%= @game.board[0] %></a></td>
          <td id='grid-1' class='top vertical-mid'><a><%= @game.board[1] %></a></td>
          <td id='grid-2' class='top right'><a><%= @game.board[2] %></a></td>
        </tr>
        <tr>
          <td id='grid-3' class='left horizontal-mid'><a><%= @game.board[3] %></a></td>
          <td id='grid-4' class='vertical-mid horizontal-mid'><a><%= @game.board[4] %></a></td>
          <td id='grid-5' class='right horizontal-mid'><a><%= @game.board[5] %></a></td>
        </tr>
        <tr>
          <td id='grid-6' class='left bottom'><a><%= @game.board[6] %></a></td>
          <td id='grid-7' class='vertical-mid bottom'><a><%= @game.board[7] %></a></td>
          <td id='grid-8' class='right bottom'><a><%= @game.board[8] %></a></td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link rel="icon" type="image/jpg" href="<%= image_url('favicon.png') %>" >
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class='navbar'>
      <%= render 'shared/navbar' %>
    </div>

    <div class="container">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= javascript_pack_tag "application" %> <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-left">

    <div class="navbar-logo">
      <%= link_to root_path do %>
        <%= image_tag "favicon.png" %>
      <% end %>
    </div>

    <div class="navbar-brand">
      <p>TicTacToe</p>
    </div>

    <div id="navbar-new">
      <div class="navbar-link">Start Game</div>
    </div>
    <div id='navbar-reset'>
      <div class="navbar-link" id="reset"><%= link_to "Reset", new_game_path %></div>
    </div>
  </div>
</div>